


###
GET http://localhost:51209/api/v1/petitions?page-size=7&page=6



###
POST http://localhost:2000/api/v1/petitions
Content-Type: application/json
Authorization: Bearer {{$auth.token("access-token")}}

{
  "title": "hello",
  "description": "world"
}

###
POST http://localhost:2000/api/v1/petitions/5a506fd7-eac8-4709-942f-2aaef27e614b/like
Authorization: Bearer {{$auth.token("access-token")}}



###
POST http://localhost:2000/api/v1/petitions/5a506fd7-eac8-4709-942f-2aaef27e614b/voice
Authorization: Bearer {{$auth.token("access-token")}}



###
DELETE http://localhost:2000/api/v1/petitions/5a506fd7-eac8-4709-942f-2aaef27e614b
Authorization: Bearer {{$auth.token("access-token")}}



###
GET http://localhost:2000/api/v1/user/likes
Authorization: Bearer {{$auth.token("access-token")}}



###
GET http://localhost:2000/api/v1/user/voices
Authorization: Bearer {{$auth.token("access-token")}}


###
GET http://localhost:2000/api/v1/user
Authorization: Bearer {{$auth.token("access-token")}}


###
GET http://localhost:8180/realms/changeit-realm/protocol/openid-connect/userinfo
Authorization: Bearer {{$auth.token("access-token")}}