version: "3.8"
name: "change-it"


services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: change-it
    ports:
      - "5432:5432"
